name: Testing
on: push

jobs: 
  test_project:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Run Django Tests
      run: |
        sudo apt update
        sudo apt install build-essential python3-dev
        pip3 install -r requirements.txt
        python3 manage.py tests liveTranscription.tests chatApp.tests transcriptionApp.tests